run_id: 0
log_level: 'DEBUG'
max_cpus: 20
gpu: None
format: tsv

mapping:
  'identity':
    type: identity
    target: 'DBpedia16_URI'
    remove_prefix: 'http://dbpedia.org/resource/'
    known_entity_files: ['dbpedia50k_train.tsv']

preprocessing:
  embeddings:
    input_files: ['dbpedia50k_train.tsv']
    models: ['TransE_l1', 'DistMult', 'ComplEx']
    epochs: 1
    batch_size: 30000

tasks:
  'dm-AAUP_classification':
    dataset: dm-AAUP
    type: classification
  'dm-AAUP_regression':
    dataset: dm-AAUP
    type: regression
  'dm-Cities_classification':
    dataset: dm-Cities
    type: classification
  'dm-Cities_regression':
    dataset: dm-Cities
    type: regression
  'dm-Forbes_classification':
    dataset: dm-Forbes
    type: classification
  'dm-Forbes_regression':
    dataset: dm-Forbes
    type: regression
  'dm-MetacriticAlbums_classification':
    dataset: dm-MetacriticAlbums
    type: classification
  'dm-MetacriticAlbums_regression':
    dataset: dm-MetacriticAlbums
    type: regression
  'dm-MetacriticMovies_classification':
    dataset: dm-MetacriticMovies
    type: classification
  'dm-MetacriticMovies_regression':
    dataset: dm-MetacriticMovies
    type: regression
  'dm-Cities2000AndCountries_clustering':
    dataset: dm-Cities2000AndCountries
    type: clustering
  'dm-CitiesAndCountries_clustering':
    dataset: dm-CitiesAndCountries
    type: clustering
  'dm-CitiesMoviesAlbumsCompaniesUni_clustering':
    dataset: dm-CitiesMoviesAlbumsCompaniesUni
    type: clustering
  'dm-Teams_clustering':
    dataset: dm-Teams
    type: clustering
  'dm-LP50_documentSimilarity':
    dataset: dm-LP50
    type: documentSimilarity
  'dm-KORE_entityRelatedness':
    dataset: dm-KORE
    type: entityRelatedness
  'dm-AllCapitalCountryEntities_semanticAnalogies':
    dataset: dm-AllCapitalCountryEntities
    type: semanticAnalogies
  'dm-CapitalCountryEntities_semanticAnalogies':
    dataset: dm-CapitalCountryEntities
    type: semanticAnalogies
  'dm-CityStateEntities_semanticAnalogies':
    dataset: dm-CityStateEntities
    type: semanticAnalogies
  'dm-CurrencyEntities_semanticAnalogies':
    dataset: dm-CurrencyEntities
    type: semanticAnalogies
  'dm-MovieLens_recommendation':
    dataset: dm-MovieLens
    type: recommendation
  'dm-LastFm_recommendation':
    dataset: dm-LastFm
    type: recommendation
  'dm-LibraryThing_recommendation':
    dataset: dm-LibraryThing
    type: recommendation
