run_id: 0

kg:
  format: tsv
  input_files: ['dbpedia50k_train.tsv']

tasks:
  'dm-AAUP_classification':
    type: dm-AAUP
    mode: classification
  'dm-AAUP_regression':
    type: dm-AAUP
    mode: regression