run_id: 0  # ID used for the collective run of all tasks; is used as name for the result folder

tasks:  # list of all tasks to be run; check the documentation in the respective task folder (./tasks/*) for details
  'dm-AAUP_classification':
    type: dm-AAUP
    mode: classification