run_id: 0  # ID used for the collective run of all tasks; is used as name for the result folder
log_level: 'INFO'  # log level (one of 'INFO', 'DEBUG', ..)
max_cpus: 1  # maximum number of CPUs to be used
gpu: None  # index of GPU to use or 'None' if no GPU should be used
format: tsv  # file input format (one of: "tsv", "nt")

preprocessing:
  embeddings:
    input_files: ['file_1.ttl', 'file_2.ttl']  # list files within the `data` folder that should be used to create embeddings
    models: ['TransE_l1', 'TransE_l2', 'TransR', 'DistMult', 'RESCAL', 'ComplEx']  # choose one or more
    epochs: 1

tasks:  # list of all tasks to be run; check the documentation in the respective task folder (./tasks/*) for details
  'dm-AAUP_classification':
    type: dm-AAUP
    mode: classification
  'dm-AAUP_regression':
    type: dm-AAUP
    mode: regression
  'dm-Cities_classification':
    type: dm-Cities
    mode: classification
  'dm-Cities_regression':
    type: dm-Cities
    mode: regression
  'dm-Forbes_classification':
    type: dm-Forbes
    mode: classification
  'dm-Forbes_regression':
    type: dm-Forbes
    mode: regression
  'dm-MetacriticAlbums_classification':
    type: dm-MetacriticAlbums
    mode: classification
  'dm-MetacriticAlbums_regression':
    type: dm-MetacriticAlbums
    mode: regression
  'dm-MetacriticMovies_classification':
    type: dm-MetacriticMovies
    mode: classification
  'dm-MetacriticMovies_regression':
    type: dm-MetacriticMovies
    mode: regression
  'dm-Cities2000AndCountries_clustering':
    type: dm-Cities2000AndCountries
    mode: clustering
  'dm-CitiesAndCountries_clustering':
    type: dm-CitiesAndCountries
    mode: clustering
  'dm-CitiesMoviesAlbumsCompaniesUni_clustering':
    type: dm-CitiesMoviesAlbumsCompaniesUni
    mode: clustering
  'dm-Teams_clustering':
    type: dm-Teams
    mode: clustering
  'dm-LP50_documentSimilarity':
    type: dm-LP50
    mode: documentSimilarity
  'dm-KORE_entityRelatedness':
    type: dm-KORE
    mode: entityRelatedness
  'dm-AllCapitalCountryEntities_semanticAnalogies':
    type: dm-AllCapitalCountryEntities
    mode: semanticAnalogies
  'dm-CapitalCountryEntities_semanticAnalogies':
    type: dm-CapitalCountryEntities
    mode: semanticAnalogies
  'dm-CityStateEntities_semanticAnalogies':
    type: dm-CityStateEntities
    mode: semanticAnalogies
  'dm-CurrencyEntities_semanticAnalogies':
    type: dm-CurrencyEntities
    mode: semanticAnalogies
  'dm-MovieLens_recommendation':
    type: dm-MovieLens
    mode: recommendation
  'dm-LastFm_recommendation':
    type: dm-LastFm
    mode: recommendation
  'dm-LibraryThing_recommendation':
    type: dm-LibraryThing
    mode: recommendation
