run_id: 0  # ID used for the collective run of all tasks; is used as name for the result folder
log_level: 'INFO'  # log level (one of 'INFO', 'DEBUG', ..)
max_cpus: 1  # maximum number of CPUs to be used
gpu: None  # index of GPU to use or 'None' if no GPU should be used
format: tsv  # file input format (one of: "tsv", "nt", "yago")

mapping:
  'identity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/identity  # mapper type: identity
    target: 'DBpedia16_URI'  # target column to map against
    known_entity_files: ['file1', 'file2', 'file3']  # use subjects of the files' triples as sum of entities of KG
    remove_prefix: 'target-prefix-to-be-removed'  # a prefix of the target column that should be removed before mapping
  'sameAs':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/sameAs  # mapper type: sameAs
    kg_prefix: 'http://example.org/resource/'  # prefix of the source KG to be mapped against
    input_files: ['file1', 'file2']  # files containing the same-as links
    additional_predicates: ['pred1', 'pred2']  # additional predicates (other than owl:sameAs) to use
  'label':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/label  # mapper type: label
    input_files: ['file1', 'file2']  # files containing labels
    label_predicates: ['http://www.w3.org/2000/01/rdf-schema#label']  # predicates used to retrieve labels
    definitive_matches_only: False  # set to true if an entity should only be mapped if there is a single exact match to its label
    similarity_threshold: 0.7  # lower threshold of acceptable similarity between labels (set to 1 for exact matches only)
    chunk_size: 1000  # number of entities mapped at once; increase for better run time at the cost of more memory


preprocessing:
  'embedding-lp':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-lp  # link prediction embeddings
    input_files: ['file_1.ttl', 'file_2.ttl']  # list files within the `data` folder that should be used to create embeddings
    models: ['TransE_l1', 'TransE_l2', 'TransR', 'DistMult', 'RESCAL', 'ComplEx']  # choose one or more
    epochs: 1  # number of epochs to train the embedding model for
    batch_size: 30000  # batch size to use on GPU
  'embedding-rdf2vec':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-rdf2vec  # rdf2vec embeddings
    input_files: ['file_1.ttl', 'file_2.ttl']  # list files within the `data` folder that should be used to create embeddings
    models: ['RDF2vec']  # choose one or more - currently only base variant implemented
    epochs: 5  # number of epochs to train the embedding model for
  'embedding-speedup':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-speedup  # embedding speedup
    ann_index: True  # whether to create Approx. Nearest Neighbor Search index
    small_embeddings: True  # whether to create an embedding file with entities of all datasets

task:  # list of all tasks to be run
  'dm-AAUP_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AAUP
    type: classification
  'dm-AAUP_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AAUP
    type: regression
  'dm-Cities_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities
    type: classification
  'dm-Cities_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities
    type: regression
  'dm-Forbes_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Forbes
    type: classification
  'dm-Forbes_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Forbes
    type: regression
  'dm-MetacriticAlbums_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticAlbums
    type: classification
  'dm-MetacriticAlbums_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticAlbums
    type: regression
  'dm-MetacriticMovies_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticMovies
    type: classification
  'dm-MetacriticMovies_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticMovies
    type: regression
  'dm-Cities2000AndCountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities2000AndCountries
    type: clustering
  'dm-CitiesAndCountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CitiesAndCountries
    type: clustering
  'dm-CitiesMoviesAlbumsCompaniesUni_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CitiesMoviesAlbumsCompaniesUni
    type: clustering
  'dm-Teams_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Teams
    type: clustering
  'dm-LP50_documentSimilarity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LP50
    type: documentSimilarity
  'dm-KORE_entityRelatedness':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-KORE
    type: entityRelatedness
  'dm-AllCapitalCountryEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AllCapitalCountryEntities
    type: semanticAnalogies
  'dm-CapitalCountryEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CapitalCountryEntities
    type: semanticAnalogies
  'dm-CityStateEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CityStateEntities
    type: semanticAnalogies
  'dm-CurrencyEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CurrencyEntities
    type: semanticAnalogies
  'dm-MovieLens_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MovieLens
    type: recommendation
  'dm-LastFm_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LastFm
    type: recommendation
  'dm-LibraryThing_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LibraryThing
    type: recommendation
