[tool.poetry]
name = "kgreat"
version = "1.0.0"
description = ""
authors = ["Anonymous"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "*"
pyyaml = "*"

[tool.poetry.dev-dependencies]
jupyter = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
