run_id: 0
log_level: 'DEBUG'
max_cpus: 20
gpu: None
format: nt

mapping:
  'identity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/identity
    target: 'DBpedia16_URI'
    known_entity_files: ['dbpedia-instance-types.nt.bz2', 'dbpedia-mappingbased-objects.nt.bz2']
  'label':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/label
    input_files: ['dbpedia-labels.nt.bz2']
    label_predicates: ['http://www.w3.org/2000/01/rdf-schema#label']
    definitive_matches_only:  False
    similarity_threshold: 0.7
    chunk_size: 1000

preprocessing:
  'embedding-lp':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-lp
    input_files: ['dbpedia-ontology.nt', 'dbpedia-instance-types.nt.bz2', 'dbpedia-mappingbased-objects.nt.bz2']
    models: ['TransE_l1', 'DistMult', 'ComplEx']
    epochs: 1
    batch_size: 30000
  'embedding-speedup':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-speedup
    ann_index: True
    small_embeddings: True

task:
  'dm-AAUP_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AAUP
    type: classification
  'dm-AAUP_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AAUP
    type: regression
  'dm-Cities_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities
    type: classification
  'dm-Cities_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities
    type: regression
  'dm-Forbes_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Forbes
    type: classification
  'dm-Forbes_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Forbes
    type: regression
  'dm-MetacriticAlbums_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticAlbums
    type: classification
  'dm-MetacriticAlbums_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticAlbums
    type: regression
  'dm-MetacriticMovies_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticMovies
    type: classification
  'dm-MetacriticMovies_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MetacriticMovies
    type: regression
  'dm-Cities2000AndCountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Cities2000AndCountries
    type: clustering
  'dm-CitiesAndCountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CitiesAndCountries
    type: clustering
  'dm-CitiesMoviesAlbumsCompaniesUni_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CitiesMoviesAlbumsCompaniesUni
    type: clustering
  'dm-Teams_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-Teams
    type: clustering
  'dm-LP50_documentSimilarity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LP50
    type: documentSimilarity
  'dm-KORE_entityRelatedness':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-KORE
    type: entityRelatedness
  'dm-AllCapitalCountryEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-AllCapitalCountryEntities
    type: semanticAnalogies
  'dm-CapitalCountryEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CapitalCountryEntities
    type: semanticAnalogies
  'dm-CityStateEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CityStateEntities
    type: semanticAnalogies
  'dm-CurrencyEntities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-CurrencyEntities
    type: semanticAnalogies
  'dm-MovieLens_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-MovieLens
    type: recommendation
  'dm-LastFm_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LastFm
    type: recommendation
  'dm-LibraryThing_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-LibraryThing
    type: recommendation
