run_id: 0  # ID used for the collective run of all tasks; is used as name for the result folder
log_level: 'DEBUG'  # log level (one of 'INFO', 'DEBUG', ..)
max_cpus: 10  # maximum number of CPUs to be used
gpu: '3'  # index of GPU to use or 'None' if no GPU should be used
format: nt  # file input format (one of: "tsv", "nt", "yago")

mapping:
  'identity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/identity
    target: 'DBpedia16_URI'
    known_entity_files: ['instance_types_en.ttl.bz2', 'mappingbased_objects_en.ttl.bz2']
  'label':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/mapping/label  # mapper type: label
    input_files: ['labels.ttl', 'labels_en.ttl.bz2']  # files containing labels
    label_predicates: ['http://www.w3.org/2000/01/rdf-schema#label']  # predicates used to retrieve labels
    definitive_matches_only:  False  # set to true if an entity should only be mapped if there is a single exact match to its label
    similarity_threshold: 1.0  # lower threshold of acceptable similarity between labels (set to 1 for exact matches only)
    chunk_size: 1000

preprocessing:
  'embedding-lp':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-lp
    input_files: ['infobox-properties.ttl', 'infobox-template-type.ttl', 'template-type.ttl', 'article-categories.ttl', 'instance_types_en.ttl.bz2', 'mappingbased_objects_en.ttl.bz2', 'dbpedia_2016-10.nt']
    models: ['TransE_l1', 'DistMult', 'ComplEx']
    epochs: 1
    batch_size: 30000
  'embedding-rdf2vec':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-rdf2vec
    input_files: ['infobox-properties.ttl', 'infobox-template-type.ttl', 'template-type.ttl', 'article-categories.ttl', 'instance_types_en.ttl.bz2', 'mappingbased_objects_en.ttl.bz2', 'dbpedia_2016-10.nt']
    models: ['RDF2vec']
    epochs: 5
  'embedding-speedup':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/preprocessing/embedding-speedup
    ann_index: True
    small_embeddings: True

task:
  'dm-aaup_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-aaup
    type: classification
  'dm-aaup_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-aaup
    type: regression
  'dm-cities_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-cities
    type: classification
  'dm-cities_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-cities
    type: regression
  'dm-forbes_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-forbes
    type: classification
  'dm-forbes_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-forbes
    type: regression
  'dm-metacriticalbums_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-metacriticalbums
    type: classification
  'dm-metacriticalbums_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-metacriticalbums
    type: regression
  'dm-metacriticmovies_classification':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-metacriticmovies
    type: classification
  'dm-metacriticmovies_regression':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-metacriticmovies
    type: regression
  'dm-cities2000andcountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-cities2000andcountries
    type: clustering
  'dm-citiesAndCountries_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-citiesAndCountries
    type: clustering
  'dm-citiesmoviesalbumscompaniesuni_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-citiesmoviesalbumscompaniesuni
    type: clustering
  'dm-teams_clustering':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-teams
    type: clustering
  'dm-lp50_documentSimilarity':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-lp50
    type: documentSimilarity
  'dm-kore_entityRelatedness':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-kore
    type: entityRelatedness
  'dm-allcapitalcountryentities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-allcapitalcountryentities
    type: semanticAnalogies
  'dm-capitalcountryentities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-capitalcountryentities
    type: semanticAnalogies
  'dm-citystateentities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-citystateentities
    type: semanticAnalogies
  'dm-currencyentities_semanticAnalogies':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-currencyentities
    type: semanticAnalogies
  'dm-movielens_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-movielens
    type: recommendation
  'dm-lastfm_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-lastfm
    type: recommendation
  'dm-librarything_recommendation':
    image: gitlab.dws.informatik.uni-mannheim.de:5050/nheist/kgreat/dataset/dm-librarything
    type: recommendation
