run_id: 0
log_level: 'DEBUG'
max_cpus: 20
gpu: None
format: yago

mapping:
  'identity':
    type: identity
    target: 'DBpedia16_URI'
    remove_prefix: 'http://dbpedia.org/resource/'
    known_entity_files: ['yagoFacts.ttl', 'yagoTypes.ttl']
  'label':
    type: label
    input_files: ['yagoLabels.ttl']
    label_predicates: ['http://www.w3.org/2000/01/rdf-schema#label', 'rdfs:label']
    definitive_matches_only:  False
    similarity_threshold: 0.7
    chunk_size: 1000

preprocessing:
  embeddings:
    input_files: ['yagoTaxonomy.ttl', 'yagoFacts.ttl', 'yagoTypes.ttl']
    models: ['TransE_l1', 'DistMult', 'ComplEx']
    epochs: 1
    batch_size: 30000

tasks:
  'dm-AAUP_classification':
    dataset: dm-AAUP
    type: classification
  'dm-AAUP_regression':
    dataset: dm-AAUP
    type: regression
  'dm-Cities_classification':
    dataset: dm-Cities
    type: classification
  'dm-Cities_regression':
    dataset: dm-Cities
    type: regression
  'dm-Forbes_classification':
    dataset: dm-Forbes
    type: classification
  'dm-Forbes_regression':
    dataset: dm-Forbes
    type: regression
  'dm-MetacriticAlbums_classification':
    dataset: dm-MetacriticAlbums
    type: classification
  'dm-MetacriticAlbums_regression':
    dataset: dm-MetacriticAlbums
    type: regression
  'dm-MetacriticMovies_classification':
    dataset: dm-MetacriticMovies
    type: classification
  'dm-MetacriticMovies_regression':
    dataset: dm-MetacriticMovies
    type: regression
  'dm-Cities2000AndCountries_clustering':
    dataset: dm-Cities2000AndCountries
    type: clustering
  'dm-CitiesAndCountries_clustering':
    dataset: dm-CitiesAndCountries
    type: clustering
  'dm-CitiesMoviesAlbumsCompaniesUni_clustering':
    dataset: dm-CitiesMoviesAlbumsCompaniesUni
    type: clustering
  'dm-Teams_clustering':
    dataset: dm-Teams
    type: clustering
  'dm-LP50_documentSimilarity':
    dataset: dm-LP50
    type: documentSimilarity
  'dm-KORE_entityRelatedness':
    dataset: dm-KORE
    type: entityRelatedness
  'dm-AllCapitalCountryEntities_semanticAnalogies':
    dataset: dm-AllCapitalCountryEntities
    type: semanticAnalogies
  'dm-CapitalCountryEntities_semanticAnalogies':
    dataset: dm-CapitalCountryEntities
    type: semanticAnalogies
  'dm-CityStateEntities_semanticAnalogies':
    dataset: dm-CityStateEntities
    type: semanticAnalogies
  'dm-CurrencyEntities_semanticAnalogies':
    dataset: dm-CurrencyEntities
    type: semanticAnalogies
  'dm-MovieLens_recommendation':
    type: dm-MovieLens
    type: recommendation
  'dm-LastFm_recommendation':
    type: dm-LastFm
    type: recommendation
  'dm-LibraryThing_recommendation':
    type: dm-LibraryThing
    type: recommendation
